fix invalid rule config
fixes the following error:

```
ERROR: Passing an array of values to a property using a comma-separated string
is no longer supported since PHP_CodeSniffer 4.0.0.
The unsupported syntax was used for property "ignoredAnnotationNames"
for sniff "SlevomatCodingStandard.Namespaces.UnusedUses".
Pass array values via <element [key="..." ]value="..."> nodes instead.
```